language: python

sudo: false

env:
#  - LUA="lua=5.1"
#  - LUA="lua=5.2"
#  - LUA="lua=5.3"
   - LUA="luajit=2.0"
#  - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install kong 0.11.2-0
  - luarocks install luaunit
  - luarocks install --server=http://luarocks.org/dev luaffi

script:
  - lua test/unit/test_handler.lua