language: python

sudo: false

env:
#  - LUA="lua=5.1"
#  - LUA="lua=5.2"
#  - LUA="lua=5.3"
   - LUA="luajit=2.0"
#  - LUA="luajit=2.1"

before_install:
  - mkdir opentracing-cpp/.build
  - cd opentracing-cpp/.build
  - cmake ..
  - make
  - cd ../../
  - cp opentracing-cpp/.build/libopentracing.so .
  - pip install hererocks
  - hererocks env --$LUA --luarocks latest
  - source env/bin/activate   
  - luarocks install luaunit
  - luarocks install --server=http://luarocks.org/dev luaffi
  - luarocks install kong 0.11.2-0
 

script:
  - lua test/unit/test_handler.lua